# Generated by Django 3.1.3 on 2020-12-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_auto_20201123_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
