# Generated by Django 3.1.4 on 2020-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_drink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
